<?php

namespace Uloc\Bundle\AppBundle\Repository\App;

/**
 * ConfigMunicipioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigMunicipioRepository extends \Doctrine\ORM\EntityRepository
{
}
