<?php

namespace Uloc\Bundle\AppBundle\Repository\App;

/**
 * ConfiguracaoGlobalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfiguracaoGlobalRepository extends \Doctrine\ORM\EntityRepository
{
}
