<?php

namespace Uloc\Bundle\AppBundle\Repository\App;

/**
 * UnidadeFederativaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnidadeFederativaRepository extends \Doctrine\ORM\EntityRepository
{
}
