<?php

namespace Uloc\Bundle\AppBundle\Repository\Historico;

use Uloc\Bundle\AppBundle\Entity\Lote;

/**
 * FavoritoLoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoritoLoteRepository extends \Doctrine\ORM\EntityRepository
{

    public function findActives($usuario)
    {

        /*
         * 'SELECT l.id id, l.descricao, l.titulo, l.slug, leilao.id leilaoid,
(SELECT CONCAT(foto.id, "__SEPARE__", foto.fileExtension) FROM UlocAppBundle:FotoLote foto WHERE foto.lote = l.id and foto.destaque = 1) fotoid
 FROM UlocAppBundle:Historico\FavoritoLote f JOIN f.lote l JOIN l.leilao leilao
 WHERE f.usuario = :usuario and l.status <= :status'

        'SELECT
l.id id,
l.descricao,
l.titulo,
l.slug,
leilao.id leilaoid,
foto.id fotoid,
foto.arquivo fotoarquivo
 FROM UlocAppBundle:Historico\FavoritoLote f
 JOIN f.lote l
 JOIN l.leilao leilao
 LEFT JOIN l.fotos foto WITH foto = (SELECT MAX(ft) FROM UlocAppBundle:FotoLote ft WHERE ft.lote = l.id and ft.destaque = 1)
 WHERE f.usuario = :usuario and l.status <= :status'
         */

        $query = $this->getEntityManager()->createQuery(
            'SELECT l.id id, l.descricao, l.titulo, l.slug, leilao.id leilaoid, leilao.dataAbertura leilaoData, 
(SELECT MAX(foto.id) FROM UlocAppBundle:FotoLote foto WHERE foto.lote = l.id and foto.destaque = 1) fotoid
 FROM UlocAppBundle:Historico\FavoritoLote f JOIN f.lote l JOIN l.leilao leilao
 WHERE f.usuario = :usuario and l.status <= :status ORDER BY leilao.dataAbertura ASC'
        )
            ->setParameter('usuario', $usuario)
            ->setParameter('status', Lote::STATUS_EM_PREGAO);

        return $query->getResult();

    }

    public function findAllByUser($usuario)
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT f.id favoritoid, l.id id, l.descricao, l.titulo, l.slug, l.status, leilao.id leilaoid, leilao.dataAbertura leilaoData, 
(SELECT MAX(foto.id) FROM UlocAppBundle:FotoLote foto WHERE foto.lote = l.id and foto.destaque = 1) fotoid
 FROM UlocAppBundle:Historico\FavoritoLote f JOIN f.lote l JOIN l.leilao leilao
 WHERE f.usuario = :usuario ORDER BY leilao.dataAbertura DESC'
        )
            ->setParameter('usuario', $usuario);

        return $query->getResult();
    }

}
