<?php

namespace Uloc\Bundle\AppBundle\Repository\Historico;

use Uloc\Bundle\AppBundle\Entity\Leilao;

/**
 * FavoritoLeilaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoritoLeilaoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActives($usuario)
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT l.id, l.titulo, l.dataAbertura leilaoData 
 FROM UlocAppBundle:Historico\FavoritoLeilao f JOIN f.leilao l 
 WHERE f.usuario = :usuario and l.status <= :status ORDER BY l.dataAbertura ASC'
        )
            ->setParameter('usuario', $usuario)
            ->setParameter('status', Leilao::STATUS_EM_PREGAO);

        return $query->getResult();

    }

    public function findAllByUser($usuario)
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT 
                      l.id leilaoId, l.dataAbertura, l.tipo, l.titulo, l.status, cache.comitentes  
                      FROM UlocAppBundle:Historico\FavoritoLeilao f JOIN f.leilao l 
                      LEFT JOIN l.cache cache
                      WHERE f.usuario = :usuario ORDER BY f.id DESC'
        )
            ->setParameter('usuario', $usuario);

        return $query->getResult();
    }
}
