<?php

namespace Uloc\Bundle\AppBundle\Repository\ServicoMensagem;

/**
 * MensagemAnexoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MensagemAnexoRepository extends \Doctrine\ORM\EntityRepository
{
}
