<?php

namespace Uloc\Bundle\AppBundle\Repository\ServicoMensagem;

/**
 * MensagemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MensagemRepository extends \Doctrine\ORM\EntityRepository
{
}
