<?php

namespace Uloc\Bundle\AppBundle\Repository\ServicoMensagem;

/**
 * MensagemLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MensagemLogRepository extends \Doctrine\ORM\EntityRepository
{
}
