<?php

namespace Uloc\Bundle\AppBundle\Repository\Enderecos;

/**
 * EstabelecimentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MunicipioRepository extends \Doctrine\ORM\EntityRepository
{

    public function getMunicipiosUF ($uf) {
        $dql = "SELECT m.id, m.nome, m.ibge FROM UlocAppBundle:Enderecos\Municipio m JOIN m.uf u WHERE u.id=:ufid";
        $query = $this->getEntityManager()->createQuery($dql)->setParameter('ufid', $uf);

        return $query->getResult();
    }


}
