<?php

namespace Uloc\Bundle\AppBundle\Repository;

/**
 * AvaliacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvaliacaoRepository extends \Doctrine\ORM\EntityRepository
{
}
