<?php

namespace Uloc\Bundle\AppBundle\Repository;

/**
 * BannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @return mixed
     */
    public function findAtivos(){

        $dql = 'SELECT b FROM UlocAppBundle:Banner b WHERE b.dataExibicao <= :dataatual AND b.dataExpiracao >= :dataatual AND b.situacao = true order by b.posicao';
        $query = $this->getEntityManager()->createQuery($dql)->setParameter('dataatual', new \DateTime());
        return $query->getResult();
    }
}
