<?php

namespace Uloc\Bundle\AppBundle\Repository;
use Uloc\Bundle\AppBundle\Entity\Contato;

/**
 * ContatoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContatoRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array|Contato[]
     */
    public function findNaoRespondidos () {
        return $this->findBy(array('isRespondido' => false), array('data' => 'DESC'));
    }

    /**
     * @return array|Contato[]
     */
    public function findAll()
    {
        return $this->findBy(array(), array('data' => 'DESC'));
    }

    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findAllQueryBuilder()
    {
        return $this->createQueryBuilder('contatos' );
    }
}
