<?php

namespace Uloc\Bundle\AppBundle\Repository;

/**
 * CriterioEstabelecimentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CriterioEstabelecimentoRepository extends \Doctrine\ORM\EntityRepository
{
}
