<?php

namespace Uloc\Bundle\AppBundle\Repository;

/**
 * EstabelecimentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstabelecimentoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEstabelecimentosNames ($usuarioid) {
        $dql = "SELECT e.id, e.nomeFantasia FROM UlocAppBundle:Usuario u JOIN u.estabelecimentos e WHERE u.id=:usuarioid";
        $query = $this->getEntityManager()->createQuery($dql)->setParameter('usuarioid', $usuarioid);

        return $query->getResult();
    }

    public function getEstabelecimentosProprietario ($usuarioid) {
        $dql = "SELECT e.id, e.nomeFantasia, e.razaoSocial, e.logo, e.tipo, e.cnpj  FROM UlocAppBundle:Usuario u JOIN u.estabelecimentos e WHERE u.id=:usuarioid";
        $query = $this->getEntityManager()->createQuery($dql)->setParameter('usuarioid', $usuarioid);

        return $query->getResult();
    }
}
