<?php

namespace Uloc\Bundle\AppBundle\Repository;

/**
 * EstabelecimentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstabelecimentoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEstabelecimentosNames ($usuarioid) {
        $dql = "SELECT e.id, e.nomeFantasia FROM UlocAppBundle:Usuario u JOIN u.estabelecimentos e WHERE u.id=:usuarioid";
        $query = $this->getEntityManager()->createQuery($dql)->setParameter('usuarioid', $usuarioid);

        return $query->getResult();
    }

    public function getEstabelecimentosProprietario ($usuarioid) {
        $dql = "SELECT e.id, e.nomeFantasia, e.razaoSocial, e.logo, e.tipo, e.cnpj  FROM UlocAppBundle:Usuario u JOIN u.estabelecimentos e WHERE u.id=:usuarioid";
        $query = $this->getEntityManager()->createQuery($dql)->setParameter('usuarioid', $usuarioid);

        return $query->getResult();
    }

    public function getEstabelecimentosMunicipio ($municipioid) {

        $dql = "
         SELECT es.id, es.nomeFantasia, es.cnpj, es.razaoSocial, es.logo, es.tipo  FROM UlocAppBundle:Estabelecimento es 
          JOIN es.enderecos e  
            JOIN e.logradouro l 
              JOIN l.bairro b 
                JOIN b.municipio m
                where m.id=:municipioid";

       // $dql = "SELECT e.id, e.nomeFantasia FROM UlocAppBundle:Usuario u JOIN u.estabelecimentos e WHERE u.id=:municipioid";

        $query = $this->getEntityManager()->createQuery($dql)->setParameter('municipioid', $municipioid);

        return $query->getResult();
    }

}
