<?php

namespace Uloc\Bundle\AppBundle\Repository\Pessoa;

/**
 * AnotacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnotacaoRepository extends \Doctrine\ORM\EntityRepository
{
}
