<?php

namespace Uloc\Bundle\AppBundle\Repository\Pessoa;

/**
 * HistoricoComunicacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoricoComunicacaoRepository extends \Doctrine\ORM\EntityRepository
{
}
