<?php

namespace Uloc\Bundle\AppBundle\Repository\Pessoa;

/**
 * IdentificadorRegistradoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdentificadorRegistradoRepository extends \Doctrine\ORM\EntityRepository
{
}
