<?php

namespace Uloc\Bundle\AppBundle\Repository\Pessoa;

/**
 * PapelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PapelRepository extends \Doctrine\ORM\EntityRepository
{
}
