<?php

namespace Uloc\Bundle\AppBundle\Repository\Pessoa;

/**
 * TipoFinalidadeTelefoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoFinalidadeTelefoneRepository extends \Doctrine\ORM\EntityRepository
{
}
