<?php

namespace Uloc\Bundle\AppBundle\Repository\Permissao;

/**
 * PermissaoModuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermissaoModuloRepository extends \Doctrine\ORM\EntityRepository
{
}
