<?php

namespace Uloc\Bundle\AppBundle\Repository\Stats;

/**
 * StatsCacheDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatsCacheDataRepository extends \Doctrine\ORM\EntityRepository
{
}
