<?php

namespace Uloc\Bundle\AppBundle\Repository\Stats;

/**
 * StatsLoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatsLoteRepository extends \Doctrine\ORM\EntityRepository
{

    public function buscaLotesVisitadosRecente($usuario, $limite)
    {

        $query = $this->getEntityManager()->createQuery(
            //'SELECT stats, lote, leilao FROM UlocAppBundle:Stats\StatsLote stats JOIN stats.lote lote JOIN lote.leilao leilao WHERE stats.usuario = :usuario'
            'SELECT DISTINCT(l.id), l.id id, l.descricao, l.titulo, l.slug, l.status, leilao.id leilaoid, leilao.dataAbertura leilaoData,
(SELECT MAX(foto.id) FROM UlocAppBundle:FotoLote foto WHERE foto.lote = l.id and foto.destaque = 1) fotoid
 FROM UlocAppBundle:Stats\StatsLote f JOIN f.lote l JOIN l.leilao leilao
 WHERE f.usuario = :usuario and leilao.dataAbertura > :dateNow ORDER BY leilao.dataAbertura ASC'
        )
            ->setParameter('usuario', $usuario)
            ->setParameter('dateNow', new \DateTime('now'), \Doctrine\DBAL\Types\Type::DATETIME)
            ->setFirstResult(0)
            ->setMaxResults(3);

        return $query->getResult();

    }

}
