<?php

namespace Uloc\Bundle\AppBundle\Repository\Notificacao;

/**
 * NotificacaoUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificacaoUsuarioRepository extends \Doctrine\ORM\EntityRepository
{
}
