<?php

namespace Uloc\Bundle\AppBundle\Repository\Notificacao;

/**
 * NotificacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificacaoRepository extends \Doctrine\ORM\EntityRepository
{
}
